version: '3'

services:

   desktoplinux:
     container_name: desktop-linux-vnc
     restart: unless-stopped
     image: consol/centos-xfce-vnc
     ports:
       - 5901:5901
       - 6901:6901
     environment:
       VNC_COL_DEPTH: 24
       VNC_RESOLUTION: 1280x1024
       VNC_PW: my$VncPassword!937
